-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_type character varying NOT NULL,
  entity_id uuid NOT NULL,
  action character varying NOT NULL,
  old_values jsonb,
  new_values jsonb,
  status USER-DEFINED DEFAULT 'pending'::audit_status,
  performed_by uuid,
  reviewed_by uuid,
  review_notes text,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.users(id),
  CONSTRAINT audit_logs_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.deductions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payroll_record_id uuid,
  deduction_type USER-DEFINED NOT NULL,
  description character varying,
  amount numeric NOT NULL,
  is_pre_tax boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deductions_pkey PRIMARY KEY (id),
  CONSTRAINT deductions_payroll_record_id_fkey FOREIGN KEY (payroll_record_id) REFERENCES public.payroll_records(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  code character varying NOT NULL UNIQUE,
  manager_id uuid,
  budget numeric,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.users(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  employee_id character varying NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone character varying,
  date_of_birth date,
  hire_date date NOT NULL,
  termination_date date,
  department_id uuid,
  position character varying NOT NULL,
  base_salary numeric NOT NULL,
  employment_status USER-DEFINED DEFAULT 'active'::employment_status,
  tax_id character varying,
  bank_account_number character varying,
  bank_name character varying,
  bank_routing_number character varying,
  address text,
  city character varying,
  state character varying,
  postal_code character varying,
  country character varying DEFAULT 'United States'::character varying,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'info'::character varying,
  is_read boolean DEFAULT false,
  action_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payroll_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  pay_period_start date NOT NULL,
  pay_period_end date NOT NULL,
  payment_date date NOT NULL,
  gross_pay numeric NOT NULL,
  net_pay numeric NOT NULL,
  total_deductions numeric DEFAULT 0,
  total_taxes numeric DEFAULT 0,
  pension_contribution numeric DEFAULT 0,
  overtime_hours numeric DEFAULT 0,
  overtime_pay numeric DEFAULT 0,
  bonus numeric DEFAULT 0,
  commission numeric DEFAULT 0,
  status USER-DEFINED DEFAULT 'pending'::payment_status,
  notes text,
  processed_by uuid,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payroll_records_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT payroll_records_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(id)
);
CREATE TABLE public.payroll_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  setting_key character varying NOT NULL UNIQUE,
  setting_value jsonb NOT NULL,
  description text,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payroll_settings_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.payslips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payroll_record_id uuid,
  employee_id uuid,
  file_url text NOT NULL,
  file_path text NOT NULL,
  file_size integer,
  generated_at timestamp with time zone DEFAULT now(),
  downloaded_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payslips_pkey PRIMARY KEY (id),
  CONSTRAINT payslips_payroll_record_id_fkey FOREIGN KEY (payroll_record_id) REFERENCES public.payroll_records(id),
  CONSTRAINT payslips_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.tax_forms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  tax_year integer NOT NULL,
  form_type character varying NOT NULL,
  form_name character varying NOT NULL,
  file_url text,
  file_path text,
  issued_date date NOT NULL,
  gross_wages numeric,
  federal_tax_withheld numeric,
  state_tax_withheld numeric,
  social_security_wages numeric,
  medicare_wages numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tax_forms_pkey PRIMARY KEY (id),
  CONSTRAINT tax_forms_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'employee'::user_role,
  mfa_enabled boolean DEFAULT false,
  mfa_secret text,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);